version: '3'

services:
  financial-news-agent:
    build: .
    ports:
      - '3010:3010'
    volumes:
      - ./config.json:/usr/src/app/config.json
    environment:
      - NODE_ENV=production
      - CONFIG_PATH=/usr/src/app/config.json
    restart: unless-stopped
